spring:
  config:
    import: "optional:configtree:/mnt/secrets/adoption/"
  application:
    name: Adoption COS API
  main:
    allow-bean-definition-overriding: true
azure:
  application-insights:
    instrumentation-key: ${APP_INSIGHTS_KEY:00000000-0000-0000-0000-000000000000}

test-url: ${TEST_URL:http://localhost:4550}

uk:
  gov:
    notify:
      api:
        key: ${UK_GOV_NOTIFY_API_KEY:dummy}
        baseUrl: https://api.notifications.service.gov.uk
      email:
        templateVars:
          signInAdoptionUrl: ${NOTIFY_TEMPLATE_SIGN_IN_ADOPTION_URL:https://adoption-web.aat.platform.hmcts.net/}
          adoptionCourtEmail: some.email@justice.gov.uk
        templates:
          english:
            TEST_EMAIL: 'b60ab1ad-fe9c-4098-81a5-ad6c976b7de3'
            SAVE_SIGN_OUT: ''
            APPLICATION_SUBMITTED: 'b60ab1ad-fe9c-4098-81a5-ad6c976b7de3'
            APPLICANT_APPLICATION_SUBMITTED: 'a0aa356f-8c6f-437c-b1b9-3c321048001d'
            LOCAL_COURT_APPLICATION_SUBMITTED: '381cfc64-5016-4fe7-bd88-3ceeb163ce69'
          welsh:
            TEST_EMAIL: '75f5d6c5-0af6-437c-afe7-623399c11e7b'
            SAVE_SIGN_OUT: ''
            APPLICATION_SUBMITTED: '75f5d6c5-0af6-437c-afe7-623399c11e7b'
            APPLICANT_APPLICATION_SUBMITTED: 'dd251faa-0c40-4540-80b4-a7edb83a43f0'
            LOCAL_COURT_APPLICATION_SUBMITTED: '2960d8dd-ab3e-4265-a71d-2d81d0fd84c8'

s2s-authorised:
  services: ${S2S_AUTHORISED_SERVICES:ccd_data}

idam:
  s2s-auth:
    url: ${TEST_S2S_URL:http://localhost:4552}
    secret: ${S2S_SECRET:AAAAAAAAAAAAAAAA}
    microservice: adoption_cos_api
  api:
    url: ${IDAM_API_BASEURL:http://localhost:5000}
  systemupdate:
    username: ${IDAM_SYSTEM_UPDATE_USERNAME:dummysystemupdate@test.com}
    password: ${IDAM_SYSTEM_UPDATE_PASSWORD:dummy}
  client:
    id: 'adoption-web'
    secret: ${OAUTH2_CLIENT_SECRET:123456}
    redirect_uri: ${IDAM_API_REDIRECT_URL:http://localhost:3000/oauth2/callback}

core_case_data:
  api:
    url: ${CASE_DATA_STORE_BASEURL:http://ccd-data-store-api-aat.service.core-compute-aat.internal}
  search:
    page_size: ${CCD_SEARCH_PAGE_SIZE:100}

doc_assembly:
  url: ${DOC_ASSEMBLY_URL:http://dg-docassembly-aat.service.core-compute-aat.internal}

document_management:
  url: ${DOCUMENT_MANAGEMENT_URL:http://dm-store-aat.service.core-compute-aat.internal}

case_document_am:
  url: ${CASE_DOCUMENT_AM_BASEURL:http://ccd-case-document-am-api-aat.service.core-compute-aat.internal}

docmosis:
  templates:
    english:
      ADOPTION_APPLICATION_SUMMARY: ADO-A58-Application-EN.docx
    welsh:
      ADOPTION_APPLICATION_SUMMARY: ADO-A58-Application-CY.docx

send-letter:
  url: ${SEND_LETTER_SERVICE_BASEURL:http://rpe-send-letter-service-aat.service.core-compute-aat.internal}

bulk-action:
  min-cases: ${BULK_ACTION_BATCH_SIZE_MIN:30}
  page-size: ${BULK_ACTION_BATCH_SIZE_MAX:50}

prd:
  api:
    url: ${PRD_API_BASEURL:http://rd-professional-api-aat.service.core-compute-aat.internal}
