apiVersion: v2
appVersion: "1.0"
description: A Helm chart for adoption-cos-api App
name: adoption-cos-api
home: https://github.com/hmcts/adoption-cos-api
version: 0.0.13
maintainers:
  - name: HMCTS Adoption team
dependencies:
  - name: java
    version: 3.7.6
    repository: 'https://hmctspublic.azurecr.io/helm/v1/repo/'
  - name: ccd
    version: 7.1.0
    repository: 'https://hmctspublic.azurecr.io/helm/v1/repo/'
    tags:
        - ccd-idam-pr
  - name: xui-webapp
    version: ~0.2.1
    repository: 'https://hmctspublic.azurecr.io/helm/v1/repo/'
    condition: xui-webapp.enabled
