apiVersion: v2
appVersion: "1.0"
description: A Helm chart for adoption-cos-api App
name: adoption-cos-api
home: https://github.com/hmcts/adoption-cos-api
version: 0.0.6
maintainers:
  - name: HMCTS Adoption team
dependencies:
  - name: java
    version: 3.7.1
    repository: '@hmctspublic'
  - name: ccd
    version: 6.0.0
    repository: '@hmctspublic'
    tags:
        - ccd-idam-pr
  - name: xui-webapp
    version: ~0.2.1
    repository: '@hmctspublic'
    condition: xui-webapp.enabled
