# Don't modify this file, it is only needed for the pipeline to set the image and ingressHost
java:
  image: ${IMAGE_NAME}
  ingressHost: ${SERVICE_FQDN}
  environment:
    APP_INSIGHTS_KEY: 273cc8cd-c511-49ae-9988-9debe01d54d5
