tags:
  ccd-idam-pr: true

java:
  image: ${IMAGE_NAME}
  ingressHost: ${SERVICE_FQDN}
  environment:
    CASE_DATA_STORE_BASEURL: http://adoption-cos-api-pr-${CHANGE_ID}-ccd-data-store-api
    CASE_DOCUMENT_AM_BASEURL: http://adoption-cos-api-pr-${CHANGE_ID}-ccd-case-document-am-api
    CITIZEN_UPDATE_CASE_STATE_ENABLED: true
    APP_INSIGHTS_KEY: 273cc8cd-c511-49ae-9988-9debe01d54d5

  keyVaults:
    adoption:
      secrets:
        - name: uk-gov-notify-api-key
          alias: UK_GOV_NOTIFY_API_KEY
        - name: s2s-secret-cos-api
          alias: S2S_SECRET
        - name: idam-secret
          alias: IDAM_CLIENT_SECRET
        - name: idam-system-user-name
          alias: IDAM_SYSTEM_UPDATE_USERNAME
        - name: idam-system-user-password
          alias: IDAM_SYSTEM_UPDATE_PASSWORD

idam-pr:
  enabled: true
  releaseNameOverride: ${SERVICE_NAME}-ccd-idam-pr
  redirect_uris:
    CCD Admin:
      - https://admin-web-${SERVICE_FQDN}/oauth2redirect
    XUI:
      - https://xui-${SERVICE_FQDN}/oauth2/callback
      - http://xui-${SERVICE_FQDN}/oauth2/callback

ccd:
  ccd:
    definitionImporter:
      enabled: false
    apiGatewayWeb:
      enabled: true
    s2s:
      enabled: false
    elastic:
      enabled: true

  ingressHost: ${SERVICE_FQDN}
  ingressIP: ${INGRESS_IP}
  consulIP: ${CONSUL_LB_IP}

  global:
    idamApiUrl: https://idam-api.aat.platform.hmcts.net
    idamWebUrl: https://idam-web-public.aat.platform.hmcts.net
    dmStoreUrl: http://dm-store-aat.service.core-compute-aat.internal
    ccdAdminWebIngress: admin-web-${SERVICE_FQDN}
    ccdApiGatewayIngress: gateway-${SERVICE_FQDN}
    postgresUsername: hmcts
    postgresPassword: hmcts
    s2sUrl: http://rpe-service-auth-provider-aat.service.core-compute-aat.internal

  ccd-api-gateway-web:
    nodejs:
      imagePullPolicy: Always
      environment:
        ADDRESS_LOOKUP_TOKEN: ${ADDRESS_LOOKUP_TOKEN}
        IDAM_SERVICE_KEY: ${CCD_API_GATEWAY_S2S_KEY}
        IDAM_OAUTH2_CLIENT_SECRET: ${CCD_API_GATEWAY_OAUTH2_CLIENT_SECRET}
        PROXY_DOCUMENT_MANAGEMENT: http://dm-store-aat.service.core-compute-aat.internal
      ingressHost: gateway-${SERVICE_FQDN}
      ingressIP: ${INGRESS_IP}
      keyVaults: []

  ccd-data-store-api:
    java:
      imagePullPolicy: Always
      environment:
        DATA_STORE_DB_HOST: ${SERVICE_NAME}-postgresql
        DATA_STORE_IDAM_KEY: ${DATA_STORE_S2S_KEY}
        DATA_STORE_DEFAULT_LOG_LEVEL: info
        DATA_STORE_S2S_AUTHORISED_SERVICES: ccd_data,ccd_gw,ccd_admin,ccd_ps,adoption_cos_api,adoption_web,xui_webapp,ccd_case_document_am_api,fis_cos_api
        CCD_S2S_AUTHORISED_SERVICES_CASE_USER_ROLES: adoption_cos_api,fis_cos_api
        CCD_DM_DOMAIN: http://dm-store-aat.service.core-compute-aat.internal
        CCD_DOCUMENT_URL_PATTERN: ^https?://(((?:api-gateway\.preprod\.dm\.reform\.hmcts\.net|dm-store-aat\.service\.core-compute-aat\.internal(?::\d+)?)\/documents\/[A-Za-z0-9-]+(?:\/binary)?)|(em-hrs-api-aat\.service\.core-compute-aat\.internal(?::\d+)?\/hearing-recordings\/[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}\/segments\/[0-9]))
        IDAM_API_BASE_URL: https://idam-api.aat.platform.hmcts.net
        IDAM_OIDC_URL: https://idam-web-public.aat.platform.hmcts.net
        CASE_DOCUMENT_AM_URL: http://adoption-cos-api-pr-${CHANGE_ID}-ccd-case-document-am-api
        IDAM_OAUTH2_DATA_STORE_CLIENT_SECRET: ${IDAM_OAUTH2_DATA_STORE_CLIENT_SECRET}
        IDAM_DATA_STORE_SYSTEM_USER_USERNAME: ${IDAM_DATA_STORE_SYSTEM_USER_USERNAME}
        IDAM_DATA_STORE_SYSTEM_USER_PASSWORD: ${IDAM_DATA_STORE_SYSTEM_USER_PASSWORD}
        ELASTIC_SEARCH_ENABLED: true
        ELASTIC_SEARCH_HOSTS: ${SERVICE_NAME}-es-master:9200
        ELASTIC_SEARCH_DATA_NODES_HOSTS:  http://${SERVICE_NAME}-es-master:9200
      keyVaults: []
      ingressHost: ccd-data-store-api-${SERVICE_FQDN}
  am-role-assignment-service:
    java:
      keyVaults:
        am:
          secrets:
            - role-assignment-service-LD-SDK-KEY
  ccd-definition-store-api:
    java:
      imagePullPolicy: Always
      environment:
        DEFINITION_STORE_DB_HOST: ${SERVICE_NAME}-postgresql
        DEFINITION_STORE_IDAM_KEY: ${DEFINITION_STORE_S2S_KEY}
        IDAM_USER_URL: https://idam-web-public.aat.platform.hmcts.net
        ELASTIC_SEARCH_ENABLED: true
        ELASTIC_SEARCH_HOST: ${SERVICE_NAME}-es-master
      keyVaults: []
      ingressHost: ccd-definition-store-${SERVICE_FQDN}
  ccd-user-profile-api:
    java:
      imagePullPolicy: Always
      enviroment:
        USER_PROFILE_DB_HOST: ${SERVICE_NAME}-postgresql
      keyVaults: []
      ingressHost: ccd-user-profile-api-${SERVICE_FQDN}

  ccd-admin-web:
    nodejs:
      image: hmctspublic.azurecr.io/ccd/admin-web:latest
      ingressHost: admin-web-${SERVICE_FQDN}
      keyVaults: []
      environment:
        USER_PROFILE_DB_HOST: ${SERVICE_NAME}-postgresql
        IDAM_ADMIN_WEB_SERVICE_KEY: ${ADMIN_S2S_KEY}
        IDAM_OAUTH2_AW_CLIENT_SECRET: ${ADMIN_WEB_IDAM_SECRET}


  importer:
    userprofile:
      enabled: true
      jurisdictions:
        - ADOPTION
      users:
        - adoption_caseworker_solicitor@mailinator.com|ADOPTION|A58|Draft
        - AdoptionCaseWorkerUser@AAT.com|ADOPTION|A58|Draft
        - TEST_CASE_WORKER_USER@mailinator.com|ADOPTION|A58|Draft
        - TEST_SOLICITOR@mailinator.com|ADOPTION|A58|Draft
        - adoption_as_caseworker_admin@mailinator.com|ADOPTION|A58|Draft
        - civil_unspecified@mailinator.com|ADOPTION|A58|Draft
      userProfileDatabaseHost: ${SERVICE_NAME}-ccd-postgres
      userProfileDatabasePort: 5432
      userProfileDatabaseUser: hmcts
      userProfileDatabasePassword: hmcts
      userProfileDatabaseName: user-profile

  postgresql:
    persistence:
      enabled: false
  elasticsearch:
    nameOverride: ${SERVICE_NAME}-es
    clusterName: "es"
    imageTag: "7.17.0"
    replicas: 1
    minimumMasterNodes: 1
    antiAffinity: "soft"
    esJavaOpts: "-Xmx512m -Xms512m"
    extraEnvs:
      - name: discovery.type
        value: single-node
      - name: cluster.initial_master_nodes
        value: ""
    persistence:
      enabled: false
    ingress:
      enabled: true
      path: /
      hosts:
        - es-${SERVICE_FQDN}

xui-webapp:
  enabled: true
  nodejs:
    imagePullPolicy: Always
    releaseNameOverride: ${SERVICE_NAME}-xui-webapp
    image: hmctspublic.azurecr.io/xui/webapp:latest
    ingressHost: xui-${SERVICE_FQDN}
    environment:
      HEALTH_CCD_COMPONENT_API: http://gateway-${SERVICE_FQDN}/health
      HEALTH_CCD_DATA_API: http://${SERVICE_NAME}-ccd-data-store-api/health
      HEALTH_TERMS_AND_CONDITIONS_API: http://xui-terms-and-conditions-${SERVICE_FQDN}.service.core-compute-preview.internal/health
      SERVICES_CCD_COMPONENT_API: http://gateway-${SERVICE_FQDN}
      SERVICES_CCD_DATA_STORE_API: http://${SERVICE_NAME}-ccd-data-store-api
      SERVICES_DOCUMENTS_API_V2: http://adoption-cos-api-pr-${CHANGE_ID}-ccd-case-document-am-api
      SERVICES_CCD_CASE_ASSIGNMENT_API: http://aac-${SERVICE_FQDN}
      SERVICES_TERMS_AND_CONDITIONS: http://xui-terms-and-conditions-${SERVICE_FQDN}.service.core-compute-preview.internal
      JURISDICTIONS: ADOPTION

ccd-case-document-am-api:
  enabled: true
  java:
    releaseNameOverride: ${SERVICE_NAME}-ccd-case-document-am-api
    imagePullPolicy: Always
    image: hmctspublic.azurecr.io/ccd/case-document-am-api:latest
    ingressHost: ccd-case-document-am-api-${SERVICE_FQDN}
    environment:
      CASE_DOCUMENT_S2S_AUTHORISED_SERVICES: ccd_case_document_am_api,ccd_gw,xui_webapp,ccd_data,bulk_scan_processor,dg_docassembly_api,bulk_scan_orchestrator,adoption_cos_api,adoption_web
      DM_STORE_BASE_URL: http://dm-store-aat.service.core-compute-aat.internal
      CCD_DATA_STORE_API_BASE_URL: http://adoption-cos-api-pr-${CHANGE_ID}-ccd-data-store-api
      IDAM_USER_URL: https://idam-api.aat.platform.hmcts.net
      IDAM_S2S_URL: http://rpe-service-auth-provider-aat.service.core-compute-aat.internal

