package uk.gov.hmcts.reform.adoption.notification;

public enum EmailTemplateName {
    SAVE_SIGN_OUT,
    TEST_EMAIL,
    APPLICANT_APPLICATION_SUBMITTED,

    CITIZEN_DRAFT_APPLICATION_EXPIRING_ALERT,

    MULTI_CHILD_SUBMIT_APPLICATION_EMAIL_ALERT,

    LOCAL_COURT_APPLICATION_SUBMITTED,

    APPLICATION_SUBMITTED_TO_LOCAL_AUTHORITY,

    LOCAL_AUTHORITY_APPLICATION_SUBMITTED,

    LOCAL_AUTHORITY_APPLICATION_SUBMITTED_ACKNOWLEDGE_CITIZEN,

    LOCAL_COURT_APPLICATION_SUBMITTED_BY_LOCAL_AUTHORITY
}
