package uk.gov.hmcts.reform.adoption.notification;

public enum EmailTemplateName {
    SAVE_SIGN_OUT,
    APPLICATION_SUBMITTED,
    JOINT_APPLICANT1_ANSWERS_SENT_FOR_REVIEW,
    SOLE_APPLICANT_APPLICATION_ACCEPTED,
    SOLE_RESPONDENT_APPLICATION_ACCEPTED,
    SOLE_APPLICANT_PARTNER_HAS_NOT_RESPONDED,
    APPLICANT_SOLICITOR_NOTICE_OF_PROCEEDINGS,
    APPLICANT_NOTICE_OF_PROCEEDINGS,
    APPLICANT_SOLICITOR_SERVICE,
    GENERAL_EMAIL_PETITIONER,
}
