package uk.gov.hmcts.reform.adoption.notification;

public enum EmailTemplateName {
    SAVE_SIGN_OUT,
    TEST_EMAIL,
    APPLICANT_APPLICATION_SUBMITTED,
    LOCAL_COURT_APPLICATION_SUBMITTED,

    APPLICATION_SUBMITTED_TO_LOCAL_AUTHORITY,

    LOCAL_AUTHORITY_APPLICATION_SUBMITTED
}
