package uk.gov.hmcts.reform.adoption.adoptioncase.caseworker.event.page;

import uk.gov.hmcts.reform.adoption.adoptioncase.model.AdoptionAgencyOrLocalAuthority;
import uk.gov.hmcts.reform.adoption.adoptioncase.model.CaseData;
import uk.gov.hmcts.reform.adoption.adoptioncase.model.Children;
import uk.gov.hmcts.reform.adoption.adoptioncase.model.Guardian;
import uk.gov.hmcts.reform.adoption.adoptioncase.model.Parent;
import uk.gov.hmcts.reform.adoption.adoptioncase.model.SocialWorker;
import uk.gov.hmcts.reform.adoption.adoptioncase.model.Solicitor;
import uk.gov.hmcts.reform.adoption.common.ccd.CcdPageConfiguration;
import uk.gov.hmcts.reform.adoption.common.ccd.PageBuilder;

public class AmendOtherPartiesDetails implements CcdPageConfiguration {


    @Override
    public void addTo(PageBuilder pageBuilder) {
        buildPageWithChildDetails(pageBuilder);
    }


    private void buildPageWithChildDetails(PageBuilder pageBuilder) {
        pageBuilder.page("amendOtherParties")
            .complex(CaseData::getChildren).label("childDetaillabel1","### Child Details")
            .label("childDetaillabel2","### Child")
            .mandatory(Children::getFirstName).mandatory(Children::getLastName)
            .mandatory(Children::getDateOfBirth).mandatory(Children::getSexAtBirth).mandatory(Children::getNationality)
            .mandatory(Children::getFirstNameAfterAdoption).mandatory(Children::getLastNameAfterAdoption)
            .done().label("localGuardianLabel1","### Legal guardian (CAFCASS)")
            .mandatoryWithLabel(CaseData::getIsChildRepresentedByGuardian, "Is the child represented by a guardian?")
            .complex(CaseData::getLocalGuardian)
            .mandatory(Guardian::getName, "isChildRepresentedByGuardian=\"Yes\"")
            .mandatory(Guardian::getAddress1, "isChildRepresentedByGuardian=\"Yes\"")
            .mandatory(Guardian::getAddress2, "isChildRepresentedByGuardian=\"Yes\"")
            .mandatory(Guardian::getAddress3, "isChildRepresentedByGuardian=\"Yes\"")
            .mandatory(Guardian::getAddressTown, "isChildRepresentedByGuardian=\"Yes\"")
            .mandatory(Guardian::getAddressCounty, "isChildRepresentedByGuardian=\"Yes\"")
            .mandatory(Guardian::getAddressPostCode, "isChildRepresentedByGuardian=\"Yes\"")
            .mandatory(Guardian::getCountry, "isChildRepresentedByGuardian=\"Yes\"")
            .mandatory(Guardian::getPhoneNumber, "isChildRepresentedByGuardian=\"Yes\"")
            .mandatory(Guardian::getEmail, "isChildRepresentedByGuardian=\"Yes\"")
            .done()
            .label("childDetaillabel3","### Solicitor")
            .mandatoryWithLabel(CaseData::getIsChildRepresentedBySolicitor, "Is the child represented by a solicitor?")
            .complex(CaseData::getChildSolicitor)
            .mandatory(Solicitor::getSolicitorFirm, "isChildRepresentedBySolicitor=\"Yes\"")
            .mandatory(Solicitor::getSolicitorRef, "isChildRepresentedBySolicitor=\"Yes\"")
            .mandatory(Solicitor::getAddress1, "isChildRepresentedBySolicitor=\"Yes\"")
            .mandatory(Solicitor::getAddress2, "isChildRepresentedBySolicitor=\"Yes\"")
            .mandatory(Solicitor::getAddress3, "isChildRepresentedBySolicitor=\"Yes\"")
            .mandatory(Solicitor::getAddressTown, "isChildRepresentedBySolicitor=\"Yes\"")
            .mandatory(Solicitor::getAddressCounty, "isChildRepresentedBySolicitor=\"Yes\"")
            .mandatory(Solicitor::getAddressPostCode, "isChildRepresentedBySolicitor=\"Yes\"")
            .mandatory(Solicitor::getCountry, "isChildRepresentedBySolicitor=\"Yes\"")
            .mandatory(Solicitor::getPhoneNumber, "isChildRepresentedBySolicitor=\"Yes\"")
            .mandatory(Solicitor::getEmail, "isChildRepresentedBySolicitor=\"Yes\"")
            .done()
            .complex(CaseData::getAdopAgencyOrLA)
            .label("localauthorylable1", "### Agencies/Local authorities details")
            .label("localauthorylable2", "### Adoption agency")
            .mandatory(AdoptionAgencyOrLocalAuthority::getAdopAgencyOrLaName)
            .mandatory(AdoptionAgencyOrLocalAuthority::getAdopAgencyOrLaContactName)
            .mandatory(AdoptionAgencyOrLocalAuthority::getAdopAgencyAddressLine1)
            .mandatory(AdoptionAgencyOrLocalAuthority::getAdopAgencyAddressLine2)
            .mandatory(AdoptionAgencyOrLocalAuthority::getAdopAgencyAddressLine3)
            .mandatory(AdoptionAgencyOrLocalAuthority::getAdopAgencyTown)
            .mandatory(AdoptionAgencyOrLocalAuthority::getAdopAgencyAddressCounty)
            .mandatory(AdoptionAgencyOrLocalAuthority::getAdopAgencyPostcode)
            .mandatory(AdoptionAgencyOrLocalAuthority::getAdopAgencyCountry)
            .mandatory(AdoptionAgencyOrLocalAuthority::getAdopAgencyOrLaPhoneNumber)
            .mandatory(AdoptionAgencyOrLocalAuthority::getAdopAgencyOrLaContactEmail)
            .done()
            .label("otherAdopAgencylable1", "### Other adoption agency")
            .mandatoryWithLabel(CaseData::getHasAnotherAdopAgencyOrLA, "Is there any other adoption agency?")
            .complex(CaseData::getOtherAdopAgencyOrLA)
            .mandatory(AdoptionAgencyOrLocalAuthority::getAdopAgencyOrLaName, "hasAnotherAdopAgencyOrLA=\"Yes\"")
            .mandatory(AdoptionAgencyOrLocalAuthority::getAdopAgencyOrLaContactName, "hasAnotherAdopAgencyOrLA=\"Yes\"")
            .mandatory(AdoptionAgencyOrLocalAuthority::getAdopAgencyAddressLine1, "hasAnotherAdopAgencyOrLA=\"Yes\"")
            .mandatory(AdoptionAgencyOrLocalAuthority::getAdopAgencyAddressLine2, "hasAnotherAdopAgencyOrLA=\"Yes\"")
            .mandatory(AdoptionAgencyOrLocalAuthority::getAdopAgencyAddressLine3, "hasAnotherAdopAgencyOrLA=\"Yes\"")
            .mandatory(AdoptionAgencyOrLocalAuthority::getAdopAgencyTown, "hasAnotherAdopAgencyOrLA=\"Yes\"")
            .mandatory(AdoptionAgencyOrLocalAuthority::getAdopAgencyAddressCounty, "hasAnotherAdopAgencyOrLA=\"Yes\"")
            .mandatory(AdoptionAgencyOrLocalAuthority::getAdopAgencyPostcode, "hasAnotherAdopAgencyOrLA=\"Yes\"")
            .mandatory(AdoptionAgencyOrLocalAuthority::getAdopAgencyCountry, "hasAnotherAdopAgencyOrLA=\"Yes\"")
            .mandatory(AdoptionAgencyOrLocalAuthority::getAdopAgencyOrLaPhoneNumber, "hasAnotherAdopAgencyOrLA=\"Yes\"")
            .mandatory(AdoptionAgencyOrLocalAuthority::getAdopAgencyOrLaContactEmail,
                       "hasAnotherAdopAgencyOrLA=\"Yes\"")
            .done()
            .complex(CaseData::getChildSocialWorker)
            .label("childLocalAuthoritylable1", "### Child's local authority")
            .mandatory(SocialWorker::getLocalAuthorityName).mandatory(SocialWorker::getSocialWorkerContact)
            .mandatory(SocialWorker::getSocialWorkerAddressLine1).mandatory(SocialWorker::getSocialWorkerAddressLine2)
            .mandatory(SocialWorker::getSocialWorkerAddressLine3).mandatory(SocialWorker::getSocialWorkerTown)
            .mandatory(SocialWorker::getSocialWorkerAddressCounty).mandatory(SocialWorker::getSocialWorkerPostcode)
            .mandatory(SocialWorker::getSocialWorkerCountry).mandatory(SocialWorker::getSocialWorkerPhoneNumber)
            .mandatory(SocialWorker::getLocalAuthorityEmail)
            .done()
            .complex(CaseData::getApplicantSocialWorker)
            .label("applicantsocilaworkerlabel1", "### Applicant's local authority")
            .mandatory(SocialWorker::getLocalAuthorityName).mandatory(SocialWorker::getSocialWorkerContact)
            .mandatory(SocialWorker::getSocialWorkerAddressLine1)
            .mandatory(SocialWorker::getSocialWorkerAddressLine2).mandatory(SocialWorker::getSocialWorkerAddressLine3)
            .mandatory(SocialWorker::getSocialWorkerTown).mandatory(SocialWorker::getSocialWorkerAddressCounty)
            .mandatory(SocialWorker::getSocialWorkerPostcode).mandatory(SocialWorker::getSocialWorkerCountry)
            .mandatory(SocialWorker::getSocialWorkerPhoneNumber).mandatory(SocialWorker::getLocalAuthorityEmail)
            .done()
            .label("RespondentDetailsLabel1", "### Respondent details")
            .label("birthMotherLabel1", "### Birth mother")
            .complex(CaseData::getBirthMother)
            .mandatory(Parent::getFirstName).mandatory(Parent::getLastName)
            .mandatory(Parent::getDeceased).mandatory(Parent::getAddress1)
            .mandatory(Parent::getAddress2).mandatory(Parent::getAddress3)
            .mandatory(Parent::getAddressTown).mandatory(Parent::getAddressCounty)
            .mandatory(Parent::getAddressPostCode).mandatory(Parent::getAddressCountry)
            .mandatory(Parent::getLastAddressDate).mandatory(Parent::getToBeServed, "", "Yes")
            .done()
            .label("birthMotherSolicitorLab1", "### Solicitor")
            .mandatoryWithLabel(CaseData::getIsBirthMotherRepresentedBySolicitor,"Is the birth mother represented by a solicitor?")
            .complex(CaseData::getBirthMotherSolicitor)
            .mandatory(Solicitor::getSolicitorFirm, "isBirthMotherRepresentedBySolicitor=\"Yes\"")
            .mandatory(Solicitor::getSolicitorRef, "isBirthMotherRepresentedBySolicitor=\"Yes\"")
            .mandatory(Solicitor::getAddress1, "isBirthMotherRepresentedBySolicitor=\"Yes\"")
            .mandatory(Solicitor::getAddress2, "isBirthMotherRepresentedBySolicitor=\"Yes\"")
            .mandatory(Solicitor::getAddress3, "isBirthMotherRepresentedBySolicitor=\"Yes\"")
            .mandatory(Solicitor::getAddressTown, "isBirthMotherRepresentedBySolicitor=\"Yes\"")
            .mandatory(Solicitor::getAddressCounty, "isBirthMotherRepresentedBySolicitor=\"Yes\"")
            .mandatory(Solicitor::getAddressPostCode, "isBirthMotherRepresentedBySolicitor=\"Yes\"")
            .mandatory(Solicitor::getCountry, "isBirthMotherRepresentedBySolicitor=\"Yes\"")
            .mandatory(Solicitor::getPhoneNumber, "isBirthMotherRepresentedBySolicitor=\"Yes\"")
            .mandatory(Solicitor::getEmail, "isBirthMotherRepresentedBySolicitor=\"Yes\"")
            .done()
            .label("birthFatherLabel1", "### Birth Father")
            .complex(CaseData::getBirthFather)
            .mandatory(Parent::getFirstName).mandatory(Parent::getLastName)
            .mandatory(Parent::getDeceased).mandatory(Parent::getAddress1)
            .mandatory(Parent::getAddress2).mandatory(Parent::getAddress3)
            .mandatory(Parent::getAddressTown).mandatory(Parent::getAddressCounty)
            .mandatory(Parent::getAddressPostCode).mandatory(Parent::getAddressCountry)
            .mandatory(Parent::getLastAddressDate)
            .mandatory(Parent::getToBeServed, "", "Yes")
            .done()
            .mandatory(CaseData::getIsBirthFatherRepresentedBySolicitor)
            .complex(CaseData::getBirthFatherSolicitor)
            .mandatory(Solicitor::getSolicitorFirm, "isBirthFatherRepresentedBySolicitor=\"Yes\"")
            .mandatory(Solicitor::getSolicitorRef, "isBirthFatherRepresentedBySolicitor=\"Yes\"")
            .mandatory(Solicitor::getAddress1, "isBirthFatherRepresentedBySolicitor=\"Yes\"")
            .mandatory(Solicitor::getAddress2, "isBirthFatherRepresentedBySolicitor=\"Yes\"")
            .mandatory(Solicitor::getAddress3, "isBirthFatherRepresentedBySolicitor=\"Yes\"")
            .mandatory(Solicitor::getAddressTown, "isBirthFatherRepresentedBySolicitor=\"Yes\"")
            .mandatory(Solicitor::getAddressCounty, "isBirthFatherRepresentedBySolicitor=\"Yes\"")
            .mandatory(Solicitor::getAddressPostCode, "isBirthFatherRepresentedBySolicitor=\"Yes\"")
            .mandatory(Solicitor::getCountry, "isBirthFatherRepresentedBySolicitor=\"Yes\"")
            .mandatory(Solicitor::getPhoneNumber, "isBirthFatherRepresentedBySolicitor=\"Yes\"")
            .mandatory(Solicitor::getEmail, "isBirthFatherRepresentedBySolicitor=\"Yes\"")
            .done()
            .label("otherpersonlable1", "### Other person with parental responsibility")
            .mandatory(CaseData::getIsThereAnyOtherPersonWithParentalResponsibility)
            .complex(CaseData::getOtherParent)
            .mandatory(Parent::getFirstName, "isThereAnyOtherPersonWithParentalResponsibility=\"Yes\"")
            .mandatory(Parent::getLastName, "isThereAnyOtherPersonWithParentalResponsibility=\"Yes\"")
            .mandatory(Parent::getAddress1, "isThereAnyOtherPersonWithParentalResponsibility=\"Yes\"")
            .mandatory(Parent::getAddress2, "isThereAnyOtherPersonWithParentalResponsibility=\"Yes\"")
            .mandatory(Parent::getAddress3, "isThereAnyOtherPersonWithParentalResponsibility=\"Yes\"")
            .mandatory(Parent::getAddressTown, "isThereAnyOtherPersonWithParentalResponsibility=\"Yes\"")
            .mandatory(Parent::getAddressCounty, "isThereAnyOtherPersonWithParentalResponsibility=\"Yes\"")
            .mandatory(Parent::getAddressPostCode, "isThereAnyOtherPersonWithParentalResponsibility=\"Yes\"")
            .mandatory(Parent::getAddressCountry, "isThereAnyOtherPersonWithParentalResponsibility=\"Yes\"")
            .mandatory(Parent::getLastAddressDate, "isThereAnyOtherPersonWithParentalResponsibility=\"Yes\"")
            .mandatory(Parent::getRelationShipWithChild, "isThereAnyOtherPersonWithParentalResponsibility=\"Yes\"")
            .mandatory(Parent::getToBeServed, "isThereAnyOtherPersonWithParentalResponsibility=\"Yes\"", "Yes")
            .done()
            .label("otherParentSolicitorlabel1", "### Solicitor","isThereAnyOtherPersonWithParentalResponsibility=\"Yes\"")
            .mandatory(CaseData::getIsOtherParentRepresentedBySolicitor,"isThereAnyOtherPersonWithParentalResponsibility=\"Yes\"")
            .complex(CaseData::getOtherParentSolicitor)
            .mandatory(Solicitor::getSolicitorFirm, "isOtherParentRepresentedBySolicitor=\"Yes\"")
            .mandatory(Solicitor::getSolicitorRef, "isOtherParentRepresentedBySolicitor=\"Yes\"")
            .mandatory(Solicitor::getAddress1, "isOtherParentRepresentedBySolicitor=\"Yes\"")
            .mandatory(Solicitor::getAddress2, "isOtherParentRepresentedBySolicitor=\"Yes\"")
            .mandatory(Solicitor::getAddress3, "isOtherParentRepresentedBySolicitor=\"Yes\"")
            .mandatory(Solicitor::getAddressTown, "isOtherParentRepresentedBySolicitor=\"Yes\"")
            .mandatory(Solicitor::getAddressCounty, "isOtherParentRepresentedBySolicitor=\"Yes\"")
            .mandatory(Solicitor::getAddressPostCode, "isOtherParentRepresentedBySolicitor=\"Yes\"")
            .mandatory(Solicitor::getCountry, "isOtherParentRepresentedBySolicitor=\"Yes\"")
            .mandatory(Solicitor::getPhoneNumber, "isOtherParentRepresentedBySolicitor=\"Yes\"")
            .mandatory(Solicitor::getEmail, "isOtherParentRepresentedBySolicitor=\"Yes\"")
            .done();
    }
}
