name: Adoption-COS-API CI

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Set up JDK 17
#     - name: Set up JDK 11 - 17 needs a regression test if it's needed. Remove this when done.
        uses: actions/setup-java@v1
        with:
          java-version: 17
#         java-version: 11 - 17 needs a regression test if it's needed. Remove this when done.
      - name: Build
        run: ./gradlew check
